module.exports=
{
    hardeep:function(){
        return("Singh");
    }
    ,
    sourav:function(){
        return("burnwal")
    },
    sayan:function(){
        return("singha");
    }
}